### ISSUE TITLE
Scala class is run as a script

### ISSUE THREAD

**Issue by trepidacious** [vert-x/mod-lang-scala#188]
I've just started trying out vert.x, and when using a script, I can run a simple example fine:

``` scala
vertx.createHttpServer.requestHandler { req: HttpServerRequest =>
  req.response.end("This is a Verticle script")
}.listen(8080)
```

However when I try to make this into a class, it will still attempt to run as a script:

``` scala
import org.vertx.scala.platform.Verticle

class Server extends Verticle {
  override def start() {
    vertx.createHttpServer.requestHandler { req: HttpServerRequest =>
      req.response.end("This is a Verticle script\n")
    }.listen(8080)
  }
}
```

This gives the following output:

```
Compiling Server.scala as Scala script 
Starting Server.scala 
Succeeded in deploying verticle
```

Connecting to localhost:8080 gives a connection refused - I assume that the "script" above runs, but just defines a class then does nothing to actually serve anything.

Looking at the code it seems like .scala files are only treated as a class if compilation as a script fails, in this case this seems to be incorrect?

**Comment by galderz** [comment]
Thanks @Narigo for stepping in :)
